### ISSUE TITLE
是否支持故障转移

### ISSUE THREAD

**Issue by LucasDove** [holdno/gopherCron#1]
可以通过配置文件指定某个节点所受理的业务线，从而做到业务统一管理但隔离调度

项目描述中说是通过配置文件指定某个节点所受理的业务线，那就是说哪个节点跑什么任务是配置写死的，无法做到故障转移？

**Comment by holdno** [comment]
比如有业务A和业务B
可能机器a只有业务A的agent 而机器b则有业务A和B的agent
那可以配置 机器a只受理业务A 机器b同事受理业务A和B

client A config:
``` toml 
projects = ["project_a"]
```

client B config:
``` toml
projects = ["project_a", "project_b"]
```
