### ISSUE TITLE
同一个任务只能在一个节点运行能否可以在所有节点运行比如处理log日志

### ISSUE THREAD

**Issue by qist** [holdno/gopherCron#2]
同一个任务只能在一个节点运行能否可以在所有节点运行比如处理log日志能否加入此功能

**Comment by holdno** [comment]
是指同一个任务在多个节点同时运行？

**Comment by qist** [comment]
就是同一个任务在多个节点同时运行，用这个替换系统定时任务，做日志切割等等。

**Comment by holdno** [comment]
下载最新版本(1.10.x)，任务配置界面有个禁止抢占关掉就可以了    
[release-1.10.4](https://github.com/holdno/gopherCron/releases/tag/v1.10.4)

抢占：多个节点检测到任务开始执行时开始抢锁，抢到锁的节点执行任务
禁止抢占：多个节点检测到任务开始执行时，直接执行任务

**Comment by qist** [comment]
谢谢！
