### ISSUE TITLE
项目部署不起来

### ISSUE THREAD

**Issue by quiet-dog** [holdno/gopherCron#22]
![截图 2023-06-10 11-58-31](https://github.com/holdno/gopherCron/assets/85886567/61c4e1fb-2e51-4530-901a-d0207b03b753)

**Comment by quiet-dog** [comment]
我把client和service的配置文件名换成dev,然后`app.store = sqlStore.MustSetup(conf.Mysql, wlog.With(zap.String("component", "sqlprovider")), true)`才跑起来

**Comment by quiet-dog** [comment]
`app.store = sqlStore.MustSetup(conf.Mysql, wlog.With(zap.String("component", "sqlprovider")), true)`我改成true,项目才建表了,service跑起来了,但是client跑不起来

**Comment by holdno** [comment]
嗯，true才会自动建表，client报错信息可以发出来看看
