### ISSUE TITLE
开源文档小建议

### ISSUE THREAD

**Issue by itlubber** [holdno/gopherCron#31]
对比了下大部分开源的定时任务调度系统，感觉[`gopherCron`](https://github.com/holdno/gopherCron)是最理想的，文档内容也比较丰富，但对小白可能从 0～1 还是有点困难，大佬什么时候有空能否在文档中新增一个`从 0～1 的部署教程`呀 QaQ

**Comment by holdno** [comment]
好的，近期会整一个基于docker的0~1文档

**Comment by itlubber** [comment]
感谢大佬 QaQ

**Comment by holdno** [comment]
[docker 部署](https://gophercron.ojbk.io/deployment/docker.html)  
这个不知道有没有帮到你

**Comment by itlubber** [comment]
etcd 和 mysql 安装完，然后启动服务端，前端页面显示空白的没有任何内容，不知道那里配置的有问题，启不起来QaQ

![image](https://github.com/holdno/gopherCron/assets/39397838/ddc8e094-67ca-44eb-b6af-fe1e7bb7b238)

**Comment by holdno** [comment]
可以直接去前端项目仓库把项目克隆下来本地构建一波，后面不计划把前端跟服务端放在一起了，不然前端的一些fix导致服务端也需要跟着发版

**Comment by itlubber** [comment]
好的，感谢大佬QaQ

**Comment by itlubber** [comment]
大佬您好，我在创建 `任务编排` 时会无法创建，可以帮忙看下否，是还需要配置什么东西吗QaQ

![image](https://github.com/holdno/gopherCron/assets/39397838/48882e0e-bc06-4073-9525-fe45029e0f9d)

**Comment by holdno** [comment]
有问题可以来discord讨论
