### ISSUE TITLE
请问，是否需要帮忙做 API E2E 测试

### ISSUE THREAD

**Issue by LinuxSuRen** [holdno/gopherCron#48]
我在帮一些开源项目做 E2E 测试，感兴趣的话，可以从下面的链接了解已经做了的项目。

https://github.com/LinuxSuRen/api-testing/discussions/284

**Comment by holdno** [comment]
开源项目，你们想做可以直接做，然后反馈社区大家一起修复，同时也能让更多人看到你们的项目
