### ISSUE TITLE
前端项目运行问题

### ISSUE THREAD

**Issue by ibarryyan** [holdno/gopherCron#65]
前端项目（https://github.com/holdno/gopherCronFE）
在和后端项目不在同一台机器运行时需要指定后端地址，这个方式可以通过在前端项目根目录下新建 `.env` 文件

```env
VITE_API_V1_BASE_URL=http://xxx:6306/api/v1
VITE_API_V1_WS_URL=ws://xxx:6306/api/v1/ws
```

但是编译后的前端静态文件该如何配置？配置文件路径应该放在哪里？

**Comment by holdno** [comment]
前端只能在编译前配置，配置完再编译

**Comment by ibarryyan** [comment]
> 前端只能在编译前配置，配置完再编译

建议优化一下，如果按照当前流程需要在每次改配置前进编译，会消耗不惜要的时间和算力
