### ISSUE TITLE
client端http接口问题

### ISSUE THREAD

**Issue by jwh5566** [holdno/gopherCron#7]
# 日志统一上报接口(http协议)，如配置此接口可忽略mysql的配置
report_addr = "" 
请教下  这里的http接口怎么写呢 ？？？ 直接写server的http://x.x.x.x:6306 吗？？？

在线等你的回复 谢谢

**Comment by jwh5566** [comment]
我在client 配置文件中 配置server的report_addr为上面的地址，web上面获取不到日志， 还请大神告知 这个http接口是哪一个  谢谢！

**Comment by holdno** [comment]
这个http接口是需要自定义开发的
如果没有特殊需求，直接在配置中配置mysql地址，agent会将日志直接写入mysql
